spring.application.name=Datasoft-Inventory-Management

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/datasoft_inventory
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#Server Port
server.port=8081
